const commands = [
    // Download
    {"name": "facebook", "desc": "Descarga videos de facebook.", "alias": ["/facebook", "/fb"], "category": "download", "uso": "_<url>_"},
    {"name": "mediafire", "desc": "Descarga archivos de mediafire.", "alias": ["/mediafire", "/mf"], "category": "download", "uso": "_<query|url>_"},
    {"name": "gdrive", "desc": "Descarga archivos de google drive.", "alias": ["/gdrive", "/drive"], "category": "download", "uso": "_<url>_"},
    {"name": "instagram", "desc": "Descarga videos de instagram.", "alias": ["/instagram", "/ig"], "category": "download", "uso": "_<url>_"},
    {"name": "tiktok", "desc": "Descarga videos de tiktok.", "alias": ["/tiktok", "/tt"], "category": "download", "uso": "_<url|query>_"},
    {"name": "ytmp3", "desc": "Descarga videos de youtube.", "alias": ["/play", "/mp3", "/playaudio", "/ytaudio", "/ytmp3"], "category": "download", "uso": "_<url|query>_"},
    {"name": "ytmp4", "desc": "Descarga videos de youtube.", "alias": ["/play2", "/mp4", "/playvideo", "/ytvideo", "/ytmp4"], "category": "download", "uso": "_<url|query>_"},

    // Grupo
    {"name": "bot", "desc": "Activa y desactiva el bot en el grupo.", "alias": ["/bot"], "category": "grupo", "uso": "_<on|off>_"},
    {"name": "promote", "desc": "Promueve a un usuario a administrador.", "alias": ["/promote"], "category": "grupo", "uso": "_<mention>_"},
    {"name": "demote", "desc": "Degrada a un usuario de administrador.", "alias": ["/demote"], "category": "grupo", "uso": "_<mention>_"},
    {"name": "setprimary", "desc": "Establece un bot como primario del grupo.", "alias": ["/setprimary"], "category": "grupo", "uso": "_<mention>_"},
    { "name": "warn", "desc": "Añade una advertencia a un usuario del grupo.", "alias": ["/warn"], "category": "grupo", "uso": "_<mention>_ + _<razón>_" },
    {"name": "topcount", "desc": "Top de usuarios con mas mensajes.", "alias": ["/topcount", "/topmessages", "/topmensajes", "/topmsgcount"], "category": "grupo"},
    { "name": "warns", "desc": "Muestra todas las advertencias registradas de un usuario.", "alias": ["/warns"], "category": "grupo", "uso": "_<mention>_" },
    { "name": "delwarn", "desc": "Elimina una advertencia específica de un usuario.", "alias": ["/delwarn"], "category": "grupo", "uso": "_<mention> <número|all>_" },
    { "name": "setwarnlimit", "desc": "Establece el límite máximo de advertencias permitidas en el grupo.", "alias": ["/setwarnlimit"], "category": "grupo", "uso": "_<número>_" },
    {"name": "clear", "desc": "Elimina usuarios inactivos tras 30 días, o consulta actividad con 'views'", "alias": ["/clear"], "category": "grupo", "uso": "_<delete|views>_"},
    {"name": "setgpbaner", "desc": "Cambia la imagen del grupo.", "alias": ["/setgpbaner"], "category": "grupo"},
    {"name": "setgpname", "desc": "Cambia el nombre del grupo.", "alias": ["/setgpname"], "category": "grupo", "uso": "_<text>_"},
    {"name": "setgpdesc", "desc": "Cambia la descripción del grupo.", "alias": ["/setgpdesc"], "category": "grupo", "uso": "_<text>_"},
    {"name": "closet", "desc": "Cierra y abre el grupo.", "alias": ["/closet", "/open"], "category": "grupo"},
    {"name": "options", "desc": "Desactiva o activa las configuraciones del grupo.", "alias": ["/welcome", "/bienvenidas", "/alerts", "/alertas", "/gacha", "/rpg", "/pokes", "/economy", "/economia", "/adminonly", "/onlyadmin", "/antilinks", "/antilink", "/antienlaces"], "category": "grupo", "uso": "_<on|off>_"},
    {"name": "groupinfo", "desc": "Muestra la información del grupo.", "alias": ["/groupinfo", "/gp"], "category": "grupo"},
    {"name": "tag", "desc": "Menciona a todos los usuarios del grupo.", "alias": ["/tag", "/hidetag"], "category": "grupo", "uso": "_<text>_"},
    {"name": "kick", "desc": "Expulsa a un usuario del grupo.", "alias": ["/kick"], "category": "grupo", "uso": "_<mention>_"},

    // IA
    {"name": "ia", "desc": "Realiza una petición a chatgpt.", "alias": ["/ia", "/chatgpt"], "category": "ia", "uso": "_<query>_"},

    // Info
    { "name": "allmenu", "desc": "Muestra la lista de comandos.", "alias": ["/allmenu", "/menu", "/help"], "category": "info", "uso": "_<category>_" },
    { "name": "cafi", "desc": "Muestra el host que patrocina al Socket.", "alias": ["/cafi"], "category": "info" },
    { "name": "ayuda", "desc": "Muestra información detallada sobre un comando específico.", "alias": ["/ayuda"], "category": "info", "uso": "_<comando>_" },
    {"name": "infobot", "desc": "Muestra la información del socket.", "alias": ["/infobot", "/infosocket", "/info"], "category": "info"},
    {"name": "creador", "desc": "Muestra el creador del socket.", "alias": ["/creador", "/owner"], "category": "info"},
    {"name": "ping", "desc": "Muestra la velocidad del Bot.", "alias": ["/ping", "/p"], "category": "info"},
    {"name": "report", "desc": "Envia un mensaje de reporte al Staff.", "alias": ["/report", "/reporte"], "category": "info", "uso": "_<error>_"},
    {"name": "status", "desc": "Ver el estado del Bot.", "alias": ["/status"], "category": "info"},
    {"name": "sug", "desc": "Envia un mensaje de sugerencia al Staff.", "alias": ["/sug", "/suggest"], "category": "info", "uso": "_<suggest>_"},
    {"name": "invite", "desc": "Envia una sugerencia de un grupo a los moderadores.", "alias": ["/invitar", "/invite"], "category": "info", "uso": "_<link>_"},

    // NSFW
    { "name": "xnxx", "desc": "Busca y descarga videos desde XNXX.", "alias": ["/xnxx"], "category": "nsfw", "uso": "_<query|url>_" },
    { "name": "xvideos", "desc": "Busca y descarga videos desde XVideos.", "alias": ["/xvideos"], "category": "nsfw", "uso": "_<query|url>_" },
    {"name": "danbooru", "desc": "Buscar imágenes en danbooru.", "alias": ["/danbooru", "/dbooru"], "category": "nsfw", "uso": "_<tag>_"},
    {"name": "gelbooru", "desc": "Buscar imágenes en gelbooru.", "alias": ["/gelbooru", "/gbooru"], "category": "nsfw", "uso": "_<tag>_"},
    {"name": "blowjob", "desc": "Dale una mamada a un usuario.", "alias": ["/blowjob", "/bj"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "boobjob", "desc": "Hacerle una rusa a un usuario.", "alias": ["/boobjob"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "cum", "desc": "Venirse en alguien.", "alias": ["/cum"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "fap", "desc": "Haserse una paja.", "alias": ["/fap", "/paja"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "anal", "desc": "Hacer un anal.", "alias": ["/anal"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "grabboobs", "desc": "Agarrar las tetas de un usuario.", "alias": ["/grabboobs"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "footjob", "desc": "Hacer una paja con los pies a un usuario.", "alias": ["/footjob"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "grope", "desc": "Manosear las nalgas a un usuario.", "alias": ["/grope"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "undress", "desc": "Encuerate o encuera a un usuario.", "alias": ["/undress", "/encuerar"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "sixnine", "desc": "Hacer un 69 con un usuario.", "alias": ["/sixnine", "/69"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "lickpussy", "desc": "Lamer un coño de un usuario.", "alias": ["/lickpussy"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "spank", "desc": "Darle una nalgada a un usuario.", "alias": ["/spank", "/nalgada"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "fuck", "desc": "Coger a un usuario.", "alias": ["/fuck", "/coger"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "suckboobs", "desc": "Chupar las tetas de un usuario.", "alias": ["/suckboobs"], "category": "nsfw", "uso": "_<mention>_"},

    // Perfil
    {"name": "level", "desc": "Muestra información de tu nivel y progreso.", "alias": ["/level", "/levelup", "/lvl"], "category": "profile", "uso": "_<mention>_"},
    {"name": "count", "desc": "Ver tus contadores de mensajes.", "alias": ["/count", "/mensajes", "/message", "/msgcount"], "category": "profile", "uso": "_<mention>_"},
    {"name": "marry", "desc": "Envia una solicitud de matrimonio a un usuario.", "alias": ["/marry"], "category": "profile", "uso": "_<mention>_"},
    {"name": "divorce", "desc": "Divorciate de tu pareja.", "alias": ["/divorce"], "category": "profile"},
    {"name": "profile", "desc": "Muestra tu perfil o la de un usuario.", "alias": ["/profile", "/perfil"], "category": "profile"},
    {"name": "setbirth", "desc": "Define una fecha de nacimiento a tu perfil.", "alias": ["/setbirth"], "category": "profile", "uso": "_<dia/mes/año|mes/dia>_"},
    { "name": "setpasatiempo", "desc": "Establece o cambia tu pasatiempo en el perfil.", "alias": ["/setpasatiempo", "/sethobby"], "category": "profile" },
    {"name": "delbirth", "desc": "Elimina tu fecha de nacimiento actual del perfil.", "alias": ["/delbirth"], "category": "profile"},
    { "name": "delpasatiempo", "desc": "Elimina tu pasatiempo actual del perfil.", "alias": ["/delpasatiempo", "/removehobby"], "category": "profile" },
    {"name": "setdescription", "desc": "Define una descripción a tu perfil.", "alias": ["/setdescription", "/setdesc"], "category": "profile", "uso": "_<text>_"},
    {"name": "deldescription", "desc": "Elimina tu descripción actual del perfil.", "alias": ["/deldescription", "/deldesc"], "category": "profile"},
    {"name": "setgenre", "desc": "Define un género a tu perfil.", "alias": ["/setgenre"], "category": "profile", "uso": "_<hombre|mujer>_"},
    {"name": "delgenre", "desc": "Elimina tu género actual del perfil.", "alias": ["/delgenre"], "category": "profile"},

    // Búsqueda
    {"name": "pinterest", "desc": "Busca imágenes en pinterest.", "alias": ["/pinterest", "/pin"], "category": "search", "uso": "_<query>_"},
    {"name": "imagen", "desc": "Busca imágenes en Google.", "alias": ["/imagen", "/img"], "category": "search", "uso": "_<query>_"},
    {"name": "aptoide", "desc": "Descarga aplicaciones de aptoide.", "alias": ["/aptoide", "/apk", "/apkdl"], "category": "search", "uso": "_<query>_"},
    {"name": "ytsearch", "desc": "Busca videos de youtube.", "alias": ["/ytsearch", "/search"], "category": "search", "uso": "_<query>_"},
    {"name": "tiktoksearch", "desc": "Busca videos de tiktok.", "alias": ["/ttsearch", "/tiktoksearch", "/tts"], "category": "search", "uso": "_<query>_"},

    // Sockets
    {"name": "bots", "desc": "Muestra el número de sockets conectados.", "alias": ["/bots", "/sockets"], "category": "sockets"},
    {"name": "logout", "desc": "Cierra la sesión del socket.", "alias": ["/logout"], "category": "sockets"},
    {"name": "code", "desc": "Vincular un nuevo socket a tu número.", "alias": ["/code"], "category": "sockets"},
    {"name": "self", "desc": "Haz privado o público tu socket.", "alias": ["/self"], "category": "sockets", "uso": "_<on|off>_"},
    { "name": "setbanner", "desc": "Cambiar el banner del menu.", "alias": ["/setbanner", "/setmenubanner"], "category": "sockets" },
    { "name": "seticon", "desc": "Cambiar el icon del socket.", "alias": ["/seticon"], "category": "sockets" },
    { "name": "setbotname", "desc": "Cambiar el nombre del bot.", "alias": ["/setbotname", "/setname"], "category": "sockets", "uso": "_<corto / largo>_" },
    { "name": "setbotowner", "desc": "Cambiar el dueño del bot.", "alias": ["/setbotowner"], "category": "sockets", "uso": "_<nombre|número>_" },
    { "name": "setbotcurrency", "desc": "Cambiar la moneda del bot.", "alias": ["/setbotcurrency"], "category": "sockets", "uso": "_<value>_" },
    { "name": "setbotprefix", "desc": "Cambiar el prefijo del bot.", "alias": ["/setbotprefix"], "category": "sockets", "uso": "_<value>_" },
    { "name": "setbotchannel", "desc": "Cambiar el canal del bot.", "alias": ["/setbotchannel", "/setchannel"], "category": "sockets", "uso": "_<value>_" },
    { "name": "setbotlink", "desc": "Cambiar el enlace del bot.", "alias": ["/setbotlink", "/setlink"], "category": "sockets", "uso": "_<value>_" },
    { "name": "reload", "desc": "Recarga la sesion del bot.", "alias": ["/reload"], "category": "sockets" },
    { "name": "setusername", "desc": "Cambia el nombre de usuario.", "alias": ["/setusername"], "category": "sockets", "uso": "_<value>_" },
    { "name": "setstatus", "desc": "Actualiza el estado del bot.", "alias": ["/setstatus"], "category": "sockets", "uso": "_<value>_" },
    { "name": "setpfp", "desc": "Cambiar la imagen de perfil.", "alias": ["/setpfp", "/setimage"], "category": "sockets" },
    {"name": "leave", "desc": "El bot abandona el grupo actual.", "alias": ["/leave"], "category": "sockets"},

    // Utilidades
    {"name": "sticker", "desc": "Convierte imágenes o videos a stickers.", "alias": ["/sticker", "/s"], "category": "utils"},
    {"name": "getpic", "desc": "Ver la foto de perfil de un usuario.", "alias": ["/getpic", "/pfp"], "category": "utils", "uso": "_<mention>_"},
    {"name": "tourl", "desc": "Convierte la imagen en un link.", "alias": ["/tourl"], "category": "utils"},
    {"name": "translate", "desc": "Traduce el texto al idioma especificado.", "alias": ["/translate"], "category": "utils", "uso": "_<idioma>_ + _<text>_"},
    {"name": "get", "desc": "Realiza solicitudes get a páginas web.", "alias": ["/get"], "category": "utils", "uso": "_<url>_"},
    {"name": "setmeta", "desc": "Define los metadatos para tus stickers.", "alias": ["/setmeta"], "category": "utils", "uso": "_<packname> | <author>_"},
    {"name": "hd", "desc": "Mejora la calidad de una imagen.", "alias": ["/hd"], "category": "utils"}
];